### ISSUE TITLE
Plane bearing is "forgotten" when X-Plane is paused

### ISSUE THREAD

**Issue by ghost** [foucdeg/x-plane-map-electron#10]
The plane icon stays in the right spot when paused, but the heading changes to "North".

**Comment by foucdeg** [comment]
I guess the solution is that whenever the new plane position is the same as the current one, we keep the previous heading. I'll try that.

**Comment by foucdeg** [comment]
Version 2.1.1 improved this slightly but not entirely yet.

**Comment by foucdeg** [comment]
Commit https://github.com/foucdeg/x-plane-map-electron/commit/4875769f65a81bf600c352aec1fcc0e0d8e20385 fixes this (download version 2.2.1)
