### ISSUE TITLE
No data to map when additional data outputs are selected

### ISSUE THREAD

**Issue by Aeroworx** [foucdeg/x-plane-map-electron#12]
For multi-player flights, we use a proxy to connect and send data to our online server. We also use localhost and port 49003 to send the following network data out:
(3) Speeds 
(17) Pitch, roll, & headings
(20) Latitude, longitude, & altitude.

As soon as we enable either (3) and/or (17), X-Plane-Map stops to respond. Would it be possible for you to allow the selections (3) and (17) as pseudo?

**Comment by foucdeg** [comment]
I'm surprised the map would stop to respond altogether in that situation. In my code, it's just supposed to ignore messages of type other than 20. I'll try to reproduce.

**Comment by foucdeg** [comment]
@Aeroworx I know why: when multiple items are selected, they are concatenated in a single message sorted by index. So 3 and 17 come before 20, although I'm expecting the message to start with 20. I'll improve this.

**Comment by foucdeg** [comment]
@Aeroworx fixed in version 2.2.2.

**Comment by Aeroworx** [comment]
Thank you, it now works perfectly!

Thank you for your dedicated work, it is much appreciated...
