### ISSUE TITLE
Cannot GET / ... on every platform

### ISSUE THREAD

**Issue by business-tomcat** [foucdeg/x-plane-map-electron#13]
Hi,

I cannot get map server running, not even on the same machine.
Tried it with the latest release 2.2.0 on windows, linux and mac. Tried different ports. Tried different browsers. Tried different IPs (localhost, 127.0.0.1, 192.168.0.x, external IP). No firewall running.

Every time I get `Cannot GET /`

I also clone the repo, build the release and ... same error.

Can someone please confirm, that this is not only a problem with my brain?

Thanks and greetings, Ninchenfan

**Comment by business-tomcat** [comment]
**UPDATE**

~~Currently I cannot build the app. npm breaks with an error in babel. I think it''s becaue you use babel 7 beta and something changed.~~

~~I could it get work when set babel version to 6 in package.json.~~

~~You really should commit your package-lock.json to prevent something like this. It is also suggested by npm: https://docs.npmjs.com/files/package-lock.json~~

**UPDATE TO UPDATE**

Shame on me, you are using yarn 😰

But my problem is still there. I always have the "cannot get /" error.
**Question**: it is necessary to run xplane so map server doesn't throw this error?

**Comment by business-tomcat** [comment]
Found the problem:
The map server in `server.js` serves the app directory via `express.static(path.join(appPath, 'app'))`.

At least for me the served directory (/app) only contains a `app.html`, no `index.html`. So any browser has no start page to present.

I renamed the `app.html` to `index.html`. Also changed some code, where it pointed to `app.html`.
An now the map is working in the browser 😄 

I forked your project and pushed my changes. You can have a look here: https://github.com/Ninchenfan/x-plane-map-electron/commit/b7bede25d1aaa15989a64f8a97eef5004b9865d8
If you want I can create a pull request.

PS: Thanks for the app, I really like to used it when flying! 👍

**Comment by foucdeg** [comment]
@the-business-tomcat thanks for your fix! Please open the PR. I'll investigate why things were running fine on my computer and then merge it.

I also clicked on the watch button for this repo, so that I find out about future issues faster.

**Comment by foucdeg** [comment]
@the-business-tomcat opened PR #14 , thanks!

**Comment by coxjaso** [comment]
Both of you are awesome! I was about to pull the code and start debugging myself till I fell on this  :)

**Comment by foucdeg** [comment]
@coxjaso thanks!
But as I said on PR #14 I can't really reproduce the issue, so I'm uncomfortable with merging the PR at the moment.

Would you mind joining the conversion there so I can get a better sense of what you guys were trying to do?
Thanks!

**Comment by foucdeg** [comment]
Addressed in version 2.2.1
