### ISSUE TITLE
Cannot open settings

### ISSUE THREAD

**Issue by tronchito** [foucdeg/x-plane-map-electron#16]
Hello! I'm trying to install Xplane-external-map but when I try to enter settings an error is shown: "Javascript error". 
I have uninstall the plugin and tried to install again but error persists.
Am I doing something wrong? Any help will be appreciated. Thanks a lot.

p.d: I tried 2.2.1 version with same result :-(

![capture](https://user-images.githubusercontent.com/38807866/39394596-1dc82fdc-4ad4-11e8-8a6f-ed7c65af764e.PNG)

**Comment by foucdeg** [comment]
@tronchito The screen underneath the error is already the settings page. The function to go to the settings produces this error when you are already on the settings page.
When you are on the map view, entering settings will work. 

I'll make that clearer in the next release.

**Comment by tronchito** [comment]
@foucdeg Thank you!! Great software!

**Comment by foucdeg** [comment]
Version 2.2.2 prevents this error message.
