### ISSUE TITLE
Is there a possibilty of changing the colour of the trace line in settings?

### ISSUE THREAD

**Issue by tobymutz** [foucdeg/x-plane-map-electron#17]
Hello! 

I've only recently started using the windows version of your software today and it seems to work pretty well. However on a short test flight I notice that the colour of the trace line was blue in a similar hue to water features such as rivers.

Could you consider offering the user the option of changing the colour of the trace line in settings or failing that possibly just change the default colour of the trace line to something like magenta which is highly visible and cannot be confused with any other feature in Google maps.

Many thanks for gifting this software to the X-plane community in the meantime.

Kind regards
TobyMutz

**Comment by foucdeg** [comment]
Hi @tobymutz ,

For aesthetic reasons, I was hoping I could stick to a bluish trace. In version 2.3 I added a white outline which is supposed to help distinguish the trace from the background.
But I agree with you, it's still not very visible. I'll try other colors.

**Comment by tobymutz** [comment]
Many thanks for answering my query - like I said, magenta or purple colour would be ideal in my opinion as an aircraft trace path colour.

I also wonder why this software does not seem to use the aircraft heading dataref as well as lat-lon coordinates. For instance if I was to practice a 10 mile or custom set up approach the electron map initially does not show the correct aircraft heading direction.

**Comment by foucdeg** [comment]
@tobymutz 
Latest version 2.3.3 has a new trace color :)

Regarding your other question, it is less network and CPU-intensive for the computer running X-Plane to not emit anything else than latitude, longitude and altitude, as the rest can be calculated from that.
Also, it is simpler for the map to read just a single type of dataref. I used to not be able to read more.
However, I've recently made that easier, so I could use X-Plane dataref as a source for speed and heading when available and fall back to calculating them when not. I'll think about it.

**Comment by tobymutz** [comment]
Thank you for responding and updating your software to give greater visibility and clarity to the aircraft flight trace path. If you haven't done so already, you should post this update on the X-Plane.org forum.

Once again, many thanks for your hard work.
