### ISSUE TITLE
Move map as opposed to plane?

### ISSUE THREAD

**Issue by ghost** [foucdeg/x-plane-map-electron#20]
Thank you so much for this awesome plugin! One question: is it possible to make it so the map actually moves behind the plane as opposed to the plane moving on the map? Like the car gps... I enjoy the satellite view and when I enlarge the map, the plane quickly moves off the screen.

**Comment by foucdeg** [comment]
Hello @brainwell, 

The default behaviour is for the map to "follow" the active plane.
However if you drag the map, it "detaches" itself from the active plane. To reattach it back, you can go to the side menu and click on the row corresponding to your plane. This will make the map pan to the plane and stay centered on it.

If, like a car GPS, you would also want the map to _rotate_ with the plane, that isn't currently possible with Leaflet unfortunately.

Hope that helps!

**Comment by ghost** [comment]
That worked! Thank you so much for the prompt response. Much appreciated. This is a great plugin.
