### ISSUE TITLE
Mobile: Cannot GET /

### ISSUE THREAD

**Issue by DemonRem** [foucdeg/x-plane-map-electron#8]
when i try to access the map from the pc everything cool
but when try to access from tablet or smartphone i got Cannot Get/

**Comment by foucdeg** [comment]
Sounds like a firewall issue. Your firewall needs to accept inbound TCP messages on port 8080 (so your mobile device can request data from the computer).

I'll rework the mobile version soon, the error messages and fixes should be clearer. I'll keep you posted.

**Comment by foucdeg** [comment]
Versions since 2.2 have a setup screen that will warn you against unavailable ports.
