### ISSUE TITLE
Setting the UDP rate not mentioned in setup instructions

### ISSUE THREAD

**Issue by ghost** [foucdeg/x-plane-map-electron#9]
The default rate is 20 packets per second UDP. This was causing a slowdown of X-Plane, and also your function to calculate the bearing is off due to that the changes were too small (always showed North).

**Comment by foucdeg** [comment]
The default rate works fine on my computer. I'll look into this.

**Comment by foucdeg** [comment]
Version 2.1.1 fixed the bearing being off when location doesn't change enough.

**Comment by foucdeg** [comment]
Version 2.2.2 added this issue in the [FAQ](https://xmap.fouc.net/#faq). 

(I guess a question asked once is a frequently asked question 😄)
